### PR TITLE
Warnings fix for incorrect state_class and device_class combination

### LINKED ISSUE #122: is this someting to worry about ?
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:497
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 5:56:57 AM (8 occurrences)
Last logged: 5:56:57 AM

    Entity sensor.dynamic_prices_highest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
    Entity sensor.dynamic_prices_average_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
    Entity sensor.dynamic_prices_current_percentage_of_highest_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
    Entity sensor.dynamic_prices_time_of_highest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
    Entity sensor.dynamic_prices_time_of_lowest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author

### PR DESCRIPTION
**Pull request by jyrkih**
Fixes #122, #128

### CODE REVIEW

**Comment by JaccoR** [comment]
Thanks @jyrkih !

**Comment by rotilho** [comment]
@JaccoR could you release a new version with this fix?

**Comment by Veldkornet** [comment]
Applied this fix manually. Seems to work fine.

**Comment by uermend** [comment]
How do you fix it mannually?

**Pull request merged**
